---
title: "TidyTuesday 10/21/25 - Historic UK Climate Data"
author: "Josephine Kaminaga"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggtext)

extrafont::font_import(pattern = "Grotesk")
extrafont::loadfonts(device = "win", quiet = TRUE)

tuesdata <- tidytuesdayR::tt_load('2025-10-21')

historic_station_met <- tuesdata$historic_station_met
```

How does the mean daily maximum and minimum temperatures at the UK's hottest and coldest weather stations in 2024 vary over the last 10 years?

```{r}
historic_station_met |>
  filter(year == 2024) |>
  summarise(
    .by = station,
    tmax_avg = mean(tmax, na.rm = TRUE)
  ) |>
  arrange(tmax_avg)
# coldest - lerwick hottest - heathrow

df_weather <- historic_station_met |>
  filter(year > 2013 & station %in% c("lerwick", "heathrow")) |>
  select(station, month, year, tmax)
```

```{r, message = FALSE, warning = FALSE}
cold_text <- "<span style='color:#59c2f7;'>**Coldest**</span> observation: 4.2 °C at Lerwick in 2021"
hot_text <- "<span style='color:#e85440;'>**Hottest**</span> observation: 28.3 °C at Heathrow in 2018"
plot_title <- "Variation in mean monthly high temperatures, 2014-2024"
plot_subtitle <- "Mean monthly high temperature readings at the UK's hottest (<span style='color:#e85440;'>Heathrow</span>)</p><p>and coldest (<span style='color:#59c2f7;'>Lerwick</span>) weather stations have stayed relatively consistent</p><p>over the past 10 years, with somewhat larger variation at <span style='color:#e85440;'>Heathrow</span></p><p>in the winter and summer months."

plt_weather <- df_weather |> filter(year == 2024) |>
  ggplot(aes(x = month, y = tmax)) +
  geom_line(aes(group = station, col = station),
            lwd = 1.75) +
  scale_color_discrete(palette = c("#e85440" ,"#59c2f7")) +
  geom_line(data = df_weather |>
              filter(year != 2024 & station == "lerwick"),
            aes(x = month, y = tmax, group = year),
            col = "#59c2f7",
            alpha = 0.3) +
  geom_line(data = df_weather |>
              filter(year != 2024 & station != "lerwick"),
            aes(x = month, y = tmax, group = year),
            col = "#e85440",
            alpha = 0.3) +
  annotate(
    "segment", x = 4.25, xend = 1.3, 
     y = 5.5, yend = 4.2, 
     colour = "#59c2f7", lwd = 1.2, alpha = 0.75,
     arrow = arrow(length = unit(0.5, units = "cm"))
  ) +
  geom_textbox(
    aes(x = 4.25, y = 5.6,
        label = cold_text),
    fill = "white", colour = "#59c2f7", text.colour = "black",
    box.size = 0.75, size = 3, family = "Host Grotesk Light",
    box.padding = unit(c(5.5, 3, 5.5, 3), "pt"),
    width = 0.25, hjust = 0, halign = 0.5
  ) +
  annotate(
    "segment", x = 4.75, xend = 6.8, 
     y = 26, yend = 28.3, 
     colour = "#e85440", lwd = 1.2, alpha = 0.75,
     arrow = arrow(length = unit(0.5, units = "cm"))
  ) +
  geom_textbox(
    aes(x = 1.75, y = 26,
        label = hot_text),
    fill = "white", colour = "#e85440", text.colour = "black",
    box.size = 0.75, size = 3, family = "Host Grotesk Light",
    box.padding = unit(c(5.5, 3, 5.5, 3), "pt"),
    width = 0.25, hjust = 0, halign = 0.5
  ) +
  scale_x_continuous(breaks = c(1, 3.75, 6.5, 9.25, 12),
                     labels = c("Jan.", "Apr.", "Jul.", "Sep.", "Dec.")) +
  scale_y_continuous(breaks = c(5, 10, 15, 20, 25)) +
  labs(x = NULL, y = "Mean daily max. temperature in °C",
       title = plot_title, subtitle = plot_subtitle) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18, family = "Host Grotesk Light"),
    plot.subtitle = element_markdown(size = 12, family = "Host Grotesk Light"),
    plot.title.position = "plot",
    axis.title.y = element_text(family = "Host Grotesk Light"),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    legend.position = "none"
  )

ggsave(filename = "britweather.png",
       width = 8,
       height = 6,
       plot = plt_weather)
```

